version: "3.9"

services:
  frontend:
  ### START DEV
    image: node:12.18.1
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend/app:/app
  ### END DEV
  ### START RELEASE
#    build:
#      context: .
#      dockerfile: ./frontend/frontend.Dockerfile
  ### END RELEASE
    working_dir: /app
    environment:   
      BACKEND_HOST: backend
      BACKEND_PORT: 9000
    depends_on:
      - "backend"
  backend:
    build:
      context: .
      dockerfile: ./backend/backend.Dockerfile
    depends_on:
      - "dbserver" 
    working_dir: /app
    environment:
      MYSQL_HOST: dbserver
      MYSQL_USER: root
      MYSQL_PASSWORD: p@ssw0rd!
      MYSQL_DB: caldowndb
  dbserver:
    build:
      context: .
      dockerfile: ./dbserver/dbserver.Dockerfile      
    volumes:
      - ./dbserver/data:/var/lib/mysql
  proxy:
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./proxy/proxy.Dockerfile
    ports:
      - "8080:8080"
      - "443:443"
  dbadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8081:80