version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/backend.Dockerfile
    depends_on:
      - "dbserver"
    ports:
      - "8000:5000"      
    working_dir: /app
    environment:
      MYSQL_HOST: dbserver
      MYSQL_USER: root
      MYSQL_PASSWORD: p@ssw0rd!
      MYSQL_DB: caldowndb
  dbserver:
    build:
      context: .
      dockerfile: ./dbserver/dbserver.Dockerfile
    volumes:
      - ./dbserver/data:/var/lib/mysql