CREATE TABLE users (
	id VARCHAR(36) PRIMARY KEY,
	username VARCHAR(20),
	password VARCHAR(256),
	datecreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	datelastloggedin TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	status INT NOT NULL
);

CREATE TABLE profiles(
	id VARCHAR(36) PRIMARY KEY,
	age INT NOT NULL,
	weight INT NOT NULL,
	height INT NOT NULL,
	gender INT NOT NULL,
	userid VARCHAR(36),
	datecreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (userid) REFERENCES users(id) ON DELETE CASCADE
);
	